name: le_chat
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^2.2.0
  emoji_picker: ^0.1.0

  camera: ^0.5.8+7
  firebase_storage: ^4.0.1
  image_picker: ^0.6.7+11
  multi_select_item: ^1.0.3
  flip_card: ^0.4.4
  font_awesome_flutter: ^8.10.0
  translator: ^0.1.5
  flutter_speed_dial: ^1.2.5
  story_view: ^0.12.3
  cached_network_image: ^2.3.3
  multi_image_picker: ^4.7.14


  #for database on firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.4


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
